### PR TITLE
Upgrade maven plugins

### PR DESCRIPTION
**Pull request by Cirras**
This PR upgrades all of the maven plugin dependencies.

It fixes the following error that occurred during tests:
`"Corrupted STDOUT by directly writing to native stream in forked JVM"`

This error was masking 2 failing tests in `GrammarTest`, one of which was a minor v1.1.0 regression introduced in #130.
(@zaneduffield, can you follow up and push a fix for that second failing test to this PR?)

### CODE REVIEW

**Comment by zaneduffield** [comment]
@Cirras I've pushed the fix for the ideographic space grammar issue.

**Review by fourls — APPROVED** [review]
Both changes look good. All tests are now passing - not even any silent failures 😄

**Comment by fourls** [comment]
@Cirras, Maven is now logging this warning:

image

Looks OK but something to be aware of.

**Comment by Cirras** [comment]
> @Cirras, Maven is now logging this warning:
> 
> image

Fixed in 2acc82e.

**Review by fourls — APPROVED** [review]
Confirmed that the maven-shade-plugin warnings are resolved. 
Looks good! Merging.

**Pull request merged**
